### ISSUE TITLE
sast2023-python-basic

### ISSUE THREAD

**Issue by huangshuhe** [sast-summer-training-2023/sast2023-python-basic#1]
[https://github.com/huangshuhe/sast2023.git](url)
提交人：黄舒翮

**Comment by YfLi03** [comment]
麻烦补充一下自己的学号

**Comment by huangshuhe** [comment]
2022010834

**Comment by YfLi03** [comment]
README: 整体 ok, 但是环境部分最好说明 Python 版本、怎么快捷安装依赖项，以及下面这部分我没看懂

```
streamlit run main_GUI_textinput.py
```
或：
```
streamlit run main_GUI_textinput.py
```


功能实现：不错。可以改进的地方有 UI 页面手动输入文件名不是很方便，或许可以弄个下拉选择框。

代码风格：ok，可以尝试更加美观与 pythonic 的风格
