### ISSUE TITLE
https://github.com/sast-summer-training-2023/sast2023-python-basic/issues

### ISSUE THREAD

**Issue by hahahawzx** [sast-summer-training-2023/sast2023-python-basic#10]
学号：2021010534
链接：https://github.com/hahahawzx/summer-class/tree/master/Desktop/%E6%9A%91%E5%9F%B9/all_the_thing/homework%20for%20python

**Comment by YfLi03** [comment]
说明文档：有点太简略了



游戏功能：完成了 GUI



代码风格：ok



直接把整个暑培仓库中的一部分作为作业提交链接的方式不太优雅，以及给的还是某一特定 commit 的链接。还是建议一项工程一个 git 仓库～
