### ISSUE TITLE
Python-basic作业仓库链接提交

### ISSUE THREAD

**Issue by Hayao-1111** [sast-summer-training-2023/sast2023-python-basic#11]
Python-basic作业仓库链接：https://github.com/Hayao-1111/CrossWordPuzzle
以及[App链接](https://crosswordpuzzle-summer2023-sunxl18.streamlit.app/)

提交人学号：2022311113

**Comment by YfLi03** [comment]
说明文档：特别详细👍 还有 LICENSE，合理怀疑是来暑培炸鱼的



游戏功能：好！甚至提供了 js 等没有要求的拓展功能。



代码风格：很不错
