### ISSUE TITLE
sast2023-python-basic

### ISSUE THREAD

**Issue by Bocchi7** [sast-summer-training-2023/sast2023-python-basic#13]
https://github.com/Bocchi7/sast2023-python-basic
学号：2022012401
吐槽：streamlit动一下就rerun的特性有亿点点难受，本认为非常自然的分离游戏步骤的页面的操作搞了好久才实现。另外我已经想不通在streamlit下语句执行的逻辑了……

**Comment by YfLi03** [comment]
说明文档：ok，不过注意“环境配置”部分应该说明用什么包管理器安装什么版本的包，而不是 `import streamlit`



游戏功能：完成了 gui，不过游戏逻辑稍有问题



代码风格：ok，可以完善一下 docstring 和注释


如果是对动一下 rerun 导致数据丢失的话，其实这是现代框架中比较常见的现象，会需要把持久化数据单独存储
