### ISSUE TITLE
Python_Project_Word_Game

### ISSUE THREAD

**Issue by Painkillerzzz** [sast-summer-training-2023/sast2023-python-basic#15]
https://github.com/Painkillerzzz/word_game
学号：2022012081

**Comment by YfLi03** [comment]
说明文档：ok, 可以再详细介绍一下如何通过 requirements.txt 安装环境、启动等内容



游戏功能：完成了 cli 与语言等拓展功能，也很不错👍，不过游戏逻辑稍有问题，在填入单词之间不应该显示文章哦



代码风格：挺好的
