### ISSUE TITLE
python word game

### ISSUE THREAD

**Issue by SyGl233** [sast-summer-training-2023/sast2023-python-basic#16]
https://github.com/SyGl233/python-word-game
id: 2022010755

**Comment by YfLi03** [comment]
说明文档：很详细，不错



游戏功能：完成了 gui 等拓展功能，还有西班牙语示例，很秀



代码风格：可以完善 docstring、注释，统一代码风格（ gui 版本的主函数还专门写了个 `pass` 让人感觉有点奇怪）
