### ISSUE TITLE
python-basic-cloze-test

### ISSUE THREAD

**Issue by chengsx21** [sast-summer-training-2023/sast2023-python-basic#17]
# :100: 填字游戏 - Cloze Test

> 程思翔 2021010761

## 仓库链接

+ [进入仓库](https://github.com/chengsx21/sast2023-python-basic)

## 部署链接

+ [进入部署](https://genshin.streamlit.app)

**Comment by YfLi03** [comment]
说明文档：很详细，很炸鱼（



游戏功能：功能特别完善👍（但是在填入单词之前不应该展示文章！）



代码风格：很不错
