### ISSUE TITLE
python-sast-2023-wordgame-ywang

### ISSUE THREAD

**Issue by ywang22THU** [sast-summer-training-2023/sast2023-python-basic#18]
https://github.com/ywang22THU/python-sast-2023-wordgame-ywang
学号：2022010760

**Comment by YfLi03** [comment]
说明文档：ok，但是里面会有影响运行的 typo (`-` 和 `_`)



游戏功能：除了 gui 之外还增加了网页出题功能，不过这边显示没有 rule.txt 无法运行



代码风格：不错
