### ISSUE TITLE
python-sast-2023-wordgame

### ISSUE THREAD

**Issue by wuyuhang05** [sast-summer-training-2023/sast2023-python-basic#19]
https://github.com/wuyuhang422/sast2023-wordgame

学号: 2022012393

**Comment by YfLi03** [comment]
说明文档：ok，最好指明 requirements.txt 的用法、怎么运行



游戏功能：完成了 gui 版本，但是同时需要在启动时输入参数，而不是进入界面后选择。我这边暂时没有跑出来。



代码风格：可以完善注释和 docstring，删除不必要的内容
