### ISSUE TITLE
sast2023-python-basic

### ISSUE THREAD

**Issue by jiangzizi** [sast-summer-training-2023/sast2023-python-basic#2]
git@github.com:jiangzizi/23thusumtrain_python_homework.git
提交人：江大治

**Comment by YfLi03** [comment]
麻烦补充一下自己的学号. 另外，当前的链接无法直接用浏览器访问

**Comment by YfLi03** [comment]
README: 有些太简单了，另外 requirements.txt 也没有交代怎么用。

功能实现：整体功能完成的比较多👍。有些地方不是特别直观，例如创建文章的时候，未说明需要用户手动将文章中词语挖去。

代码风格：ok，可以尝试更加美观与 pythonic 的风格，例如添加函数说明等
