### ISSUE TITLE
sast2023-python-basic-homework

### ISSUE THREAD

**Issue by QDKStorm** [sast-summer-training-2023/sast2023-python-basic#20]
https://github.com/QDKStorm/sast2023-python-basic-homework

学号：2022010487

**Comment by YfLi03** [comment]
是我来晚了吗？仓库已经不存在了orz

**Comment by QDKStorm** [comment]
> 是我来晚了吗？仓库已经不存在了orz

emmm手滑删掉了，以为是用不着的东西，现在应该能看到了

**Comment by YfLi03** [comment]
说明文档：稍有简略，应该包含怎么启动等等内容

游戏功能：完成了基础功能

代码风格：OK👌
