### ISSUE TITLE
sast-2023-python

### ISSUE THREAD

**Issue by ahydchh** [sast-summer-training-2023/sast2023-python-basic#23]
github链接：https://github.com/ahydchh/my_repository/tree/main
streamlit cloud链接：https://myrepository-dfkohoitdn.streamlit.app/
> 提交人 迟浩瀚
> 学号 2022010762

**Comment by YfLi03** [comment]
说明文档：很完善



游戏功能：很赞，完成了 gui，云端部署，有图片美化、支持下载等



代码风格：还可以。最多的地方有七层缩进，可以考虑稍微减少一些
