### ISSUE TITLE
sast2023-python-homework

### ISSUE THREAD

**Issue by dufengfeng** [sast-summer-training-2023/sast2023-python-basic#29]
学号：2022012727
https://github.com/dufengfeng/sast2023-python/tree/master/sast2023-python

**Comment by YfLi03** [comment]
说明文档：ok，不过 markdown 非必要不嵌套 html



游戏功能：完成了 gui，不错



代码风格：可以添加些注释，同时统一代码风格，例如等号两边是否有空格
