### ISSUE TITLE
homework

### ISSUE THREAD

**Issue by Tsuruko04** [sast-summer-training-2023/sast2023-python-basic#3]
https://github.com/Tsuruko04/word_game.git

**Comment by YfLi03** [comment]
麻烦补充一下自己的学号

**Comment by Tsuruko04** [comment]
2022012085

**Comment by YfLi03** [comment]
README:  建议再说明一下怎么启动游戏。

功能实现：完成了基础功能, 但是游戏逻辑好像有点问题...

代码风格：ok
