### ISSUE TITLE
sast2023-python-basic-homework #32

### ISSUE THREAD

**Issue by cosarah** [sast-summer-training-2023/sast2023-python-basic#32]
仓库地址：https://github.com/cosarah/game.git 详见 README.md 姓名：杨慎 学号：2022012073

**Comment by YfLi03** [comment]
说明文档：稍有简略，格式也可以做一定调整，此外给的样例运行方法似乎不能工作



游戏功能：完成了 gui，不过替换似乎不完全？



代码风格：用了 lambda 表达式等，不错。可以添加一些注释。
