### ISSUE TITLE
sast2023-python-basic

### ISSUE THREAD

**Issue by leverimmy** [sast-summer-training-2023/sast2023-python-basic#5]
Git: https://github.com/LeverImmy/sast2023-python-basic.git
README.md 中详细叙述了具体功能的完成情况。
同时，本游戏也部署到了 [word-game.streamlit.app](https://word-game.streamlit.app/) 上。
学号：2022011223

**Comment by leverimmy** [comment]
update: 在 examples.json 里添加了更多样例

**Comment by YfLi03** [comment]
README: 好，特别详尽

功能实现：功能很全，还部署了，书院笑话也很好笑👍

代码风格：整体不错

总之，好！
