### ISSUE TITLE
sast2023-python-basic

### ISSUE THREAD

**Issue by A-sock-puppet** [sast-summer-training-2023/sast2023-python-basic#7]
https://github.com/A-sock-puppet/sast2023-python-basic.git
芦锦森
2022012233

**Comment by YfLi03** [comment]
说明文档：好，特别详细，还给了使用图片



游戏功能：👍，丰富



代码风格：较为美观整齐



总之很厉害！不过不太清楚你使用的 requirements.txt 是哪种格式。如果是手动输入的话，可以考虑使用一下虚拟环境进行管理～
