### ISSUE TITLE
sast2023-python-basic

### ISSUE THREAD

**Issue by lishuangyuly** [sast-summer-training-2023/sast2023-python-basic#8]
https://github.com/lishuangyuly/sast2023-python-basic
姓名：李双宇
学号：2022010735

**Comment by YfLi03** [comment]
说明文档：ok



游戏功能：部分配置可以给出默认项；CLI 版本替换不完全，GUI 版本游戏逻辑稍有问题，可以改进。



代码风格：不错，添加了函数 docstring 等内容
