### ISSUE TITLE
sast2023-python-basic

### ISSUE THREAD

**Issue by zhuhz22** [sast-summer-training-2023/sast2023-python-basic#9]
提交人 朱泓舟 2022010804
仓库地址 https://github.com/zhuhz22/sast2023-python-basic
GUI版本同时部署在streamlit cloud 上，地址为 https://sast2023-word-filling.streamlit.app

**Comment by YfLi03** [comment]
说明文档：较为详细，不过不是特别建议在 markdown 里内嵌 html



游戏功能：完成了 GUI，不过逻辑稍有问题



代码风格：可以改进，例如不应该使用 `_` 作为变量名称
